# Generated by Django 3.1 on 2021-11-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(max_length=100)),
                ('currency', models.CharField(max_length=100)),
                ('card_number', models.IntegerField(max_length=100)),
                ('cvv', models.IntegerField(max_length=100)),
                ('expiry_month', models.IntegerField(max_length=100)),
                ('expiry_year', models.IntegerField(max_length=100)),
                ('text_ref', models.IntegerField(max_length=100)),
            ],
        ),
    ]
