# Generated by Django 3.1 on 2021-11-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='card_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='currency',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cvv',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='expiry_month',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='expiry_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='text_ref',
            field=models.IntegerField(),
        ),
    ]
