# Generated by Django 3.1 on 2021-11-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20211104_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='text_ref',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
