# Generated by Django 3.1 on 2021-11-04 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20211104_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='dominic@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='customer',
            name='text_ref',
            field=models.IntegerField(null=True),
        ),
    ]
